version: '3.5'

services:
 nginx:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./dist:/usr/share/nginx/www
    restart: unless-stopped

networks:
  default:
    external: true
    name: ${NETWORK_NAME:-csbookn}
